export const settings = {
  year: '2022',
  noIntervention : 0,
  orderSetNotFollowed: -10,
  intervention: -10,
  orderPrevented : -20,
  notAvailable : 0,
  numPrescriptions: 45,
  numConfigError : 2,
  // testLimit : 45,
  // numRequiredChildPatients : 1,
  numRequiredAdultPatients : 3,
  numAllRequiredPatients : 3,
  version : '2.3',
  appOpen : true,
  debugMode : true,
  skipButton: true,
};
